"use client";

import { useEffect, useRef, useState } from "react";
import { RiNotification3Line } from "@remixicon/react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/lib/auth-context";
import { apiClient } from "@/lib/api.client";

type Notification = { id: string; title: string; body?: string | null; href?: string | null; read_at?: string | null; created_at: string };
export function NotificationBell() {
  const { session } = useAuth(); const router = useRouter(); const [open, setOpen] = useState(false); const [items, setItems] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const ref = useRef<HTMLDivElement>(null);
  const load = async () => { if (!session?.access_token) return; const result: any = await apiClient.get("/api/v1/notifications?limit=12", session.access_token); setItems(result.data?.notifications ?? []); setUnread(result.data?.unreadCount ?? 0); };
  useEffect(() => { void load().catch(() => undefined); }, [session?.access_token]);
  useEffect(() => { const onNotification = (event: Event) => { const item = (event as CustomEvent<Notification>).detail; if (!item?.id) return; setItems((current) => [item, ...current.filter((candidate) => candidate.id !== item.id)].slice(0, 12)); setUnread((current) => current + 1); }; window.addEventListener("classphere:notification", onNotification); return () => window.removeEventListener("classphere:notification", onNotification); }, []);
  useEffect(() => { const close = (event: MouseEvent) => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const openItem = async (item: Notification) => { if (!item.read_at && session?.access_token) { await apiClient.post(`/api/v1/notifications/${item.id}/read`, {}, session.access_token).catch(() => undefined); setItems((current) => current.map((candidate) => candidate.id === item.id ? { ...candidate, read_at: new Date().toISOString() } : candidate)); setUnread((current) => Math.max(0, current - 1)); } setOpen(false); if (item.href) router.push(item.href); };
  const markAllRead = async () => { if (!session?.access_token || !unread) return; await apiClient.post("/api/v1/notifications/read-all", {}, session.access_token); setItems((current) => current.map((item) => ({ ...item, read_at: item.read_at ?? new Date().toISOString() }))); setUnread(0); };
  return <div ref={ref} className="relative"><button onClick={() => { setOpen((value) => !value); if (!open) void load().catch(() => undefined); }} aria-label="Notifications" className="relative flex size-12 items-center justify-center rounded-full bg-b-surface2 border border-s-stroke2 transition-all active:scale-95 shadow-widget hover:border-s-highlight cursor-pointer shrink-0 text-t-secondary hover:text-t-primary"><RiNotification3Line size={20} />{unread > 0 && <span className="absolute right-2 top-2 flex min-w-4 h-4 items-center justify-center rounded-full bg-primary-03 px-1 text-[9px] font-bold text-white">{unread > 9 ? "9+" : unread}</span>}</button>{open && <div className="absolute bottom-14 left-0 z-50 w-[min(22rem,calc(100vw-2rem))] overflow-hidden rounded-[14px] border border-s-stroke2 bg-b-surface1 shadow-depth"><div className="flex items-center justify-between border-b border-s-stroke2 px-4 py-3"><p className="font-semibold text-t-primary">Notifications</p><button onClick={() => void markAllRead()} className="text-xs font-semibold text-primary-01 disabled:opacity-50" disabled={!unread}>Mark all read</button></div><div className="max-h-80 overflow-y-auto">{items.length ? items.map((item) => <button key={item.id} onClick={() => void openItem(item)} className={`block w-full border-b border-s-stroke2/70 px-4 py-3 text-left transition-colors hover:bg-b-surface2 ${item.read_at ? "" : "bg-primary-01/5"}`}><p className="text-sm font-semibold text-t-primary">{item.title}</p>{item.body && <p className="mt-1 text-xs leading-5 text-t-secondary">{item.body}</p>}</button>) : <p className="px-4 py-8 text-center text-sm text-t-secondary">You’re all caught up.</p>}</div></div>}</div>;
}
