content = open("/home/harshsinghsv/Projects/test-jee-neet/docs/analysis_engine.md", "w")
content.write("# ExamPrep — Analysis Engine v2: Complete Technical Documentation\n\n")
content.write("> **Version:** 2.0 | **Status:** Pre-implementation | **Classification:** Internal Engineering Reference\n\n")
content.write("---\n\n")
content.write("## Table of Contents\n\n")
content.write("1. [Overview & Philosophy](#1-overview--philosophy)\n")
content.write("2. [Pipeline Architecture](#2-pipeline-architecture)\n")
content.write("3. [Question Schema Contract](#3-question-schema-contract)\n")
content.write("4. [TypeScript Type Definitions](#4-typescript-type-definitions)\n")
content.write("5. [Stage 1 — Scoring](#5-stage-1--scoring)\n")
content.write("6. [Stage 2 — Mistake Classifier](#6-stage-2--mistake-classifier)\n")
content.write("7. [Stage 3 — Topic Accuracy](#7-stage-3--topic-accuracy)\n")
content.write("8. [Stage 4 — Error Pattern Detection](#8-stage-4--error-pattern-detection)\n")
content.write("9. [Stage 5 — Free Marks Calculator](#9-stage-5--free-marks-calculator)\n")
content.write("10. [Stage 6 — Skip Analysis](#10-stage-6--skip-analysis)\n")
content.write("11. [Stage 7 — Study Plan Generator](#11-stage-7--study-plan-generator)\n")
content.write("12. [Stage 8 — Booster Config](#12-stage-8--booster-config)\n")
content.write("13. [Stage 9 — Batch Analysis](#13-stage-9--batch-analysis)\n")
content.write("14. [Master Orchestrator](#14-master-orchestrator)\n")
content.write("15. [Database Schema Changes](#15-database-schema-changes)\n")
content.write("16. [File Structure](#16-file-structure)\n")
content.write("17. [API Integration](#17-api-integration)\n")
content.write("18. [Implementation Roadmap](#18-implementation-roadmap)\n")
content.write("19. [Error Taxonomy Reference](#19-error-taxonomy-reference)\n")
content.write("20. [Testing Strategy](#20-testing-strategy)\n\n")
content.write("---\n\n")
content.close()
print("Header written")
